---
- name: Install collectd on all host
  hosts: "{{ openstack_host_group|default('hosts') }}"
  user: root
  tasks:
  apt: pkg=collectd={{ collectd_version }}
       install_recommends={{ collectd_install_recommends }}
       state=present
  vars_files:
    - "{{ haproxy_keepalived_vars_file | default('config-keepalived/keepalived_haproxy.yml') }}"
- name: Configure Collectd
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify:
    - Restart Collectd

- name: Restart Collectd
  service: name=collectd state=restarted