---
cidr_networks:
  container: 10.2.0.0/23  # br-mgmt
  tunnel: 10.3.0.0/24     # br-vxlan
  storage: 10.4.0.0/24    # br-storage
  monitor: 10.5.0.0/24    # br-monlog

used_ips:
  - "10.2.0.1,10.2.0.159"
  - "10.3.0.1,10.3.0.159"
  - "10.4.0.1,10.4.0.159"
  - "10.5.0.1,10.5.0.159"


lxc_container_domain: "production.local"

global_overrides:
  internal_lb_vip_address: "{{ internal_vip }}"
  external_lb_vip_address: "{{ horizon_domain }}"
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  monlog_bridge: "br-monlog"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:10000"
        container_mtu: "9000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
          - neutron_openswitch_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth3"
        ip_from_q: "storage"
        container_mtu: "9000"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
    - network:
        container_bridge: "br-monlog"
        container_type: "veth"
        container_interface: "eth4"
        ip_from_q: "monitor"
        container_mtu: "1500"
        type: "raw"
        group_binds:
          - rabbitmq_all
          - galera_all
          - hosts
