---
# Region
service_region: TH-SRB
openstack_service_publicuri_proto: https
#ironic_service_region: "{{ service_region }}"
#swift_service_region: "{{ service_region }}"
#magnum_service_region: "{{ service_region }}"
#octavia_service_region: "{{ service_region }}"

# SQLAlchemy/Olso Thread Pool Settings
rpc_conn_pool_size: 180 # default is 30
rpc_response_timeout: 180 # default is 60
rpc_thread_pool_size: 180 # default is 100

db_max_overflow: 60 # default 10
db_max_pool_size: 120 # default 120
db_pool_timeout: 60 # default 30


memcached_connections: 16384 # default 4096

# NTP Be verify
security_ntp_servers:
  - clock.nectec.or.th
  - ntp.ku.ac.th